apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-k8s-frontend-deployment
  labels:
    app: yolo-k8s-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-k8s-frontend
  template:
    metadata:
      labels:
        app: yolo-k8s-frontend
    spec:
      containers:
      - name: yolo-k8s-frontend
        image: yolo-frontend:latest
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
        env:
            - name: baseurl
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: baseurl